build: support building against Foundation.framework
This enables building XCTest against the System Foundation.framework on
macOS.  This requires that the executable path is computed using `URL`
(`NSURL`) as the `lastPathComponent` has been explicitly made
unavailable.

```
/Users/compnerd/SourceCache/swift-corelibs-xctest/Sources/XCTest/Public/XCTestMain.swift:99:48: error: 'lastPathComponent' is unavailable: Use lastPathComponent on URL instead.
        let exeName = CommandLine.arguments[0].lastPathComponent
                                               ^~~~~~~~~~~~~~~~~
Foundation.StringProtocol:7:16: note: 'lastPathComponent' has been explicitly marked unavailable here
    public var lastPathComponent: String { get }
               ^
```